# Generated by Django 4.2.2 on 2023-06-29 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='points',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='priority',
            field=models.CharField(default='Baixa', max_length=10),
        ),
    ]
