# Generated by Django 4.2.2 on 2023-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_occurrence_citizen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='citizen_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
