# Generated by Django 4.2.2 on 2023-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_occurrence_citizen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
