# Generated by Django 4.2.2 on 2023-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_occurrence_latitude_occurrence_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='cep',
            field=models.CharField(default='37540-000', max_length=10),
        ),
    ]
