# Generated by Django 4.2.2 on 2023-07-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_occurrence_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='cep',
            field=models.CharField(default='37540-000', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='cep',
            field=models.CharField(default='37540-000', max_length=10),
        ),
    ]
