# Generated by Django 4.2.2 on 2023-07-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_citizen_cep_city_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
