# Generated by Django 4.2.2 on 2023-07-17 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_citizen_cep_alter_city_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
    ]
