# Generated by Django 4.2.2 on 2023-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_citizen_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='cep',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
