# Generated by Django 4.2.2 on 2023-07-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_citizen_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
        migrations.AlterField(
            model_name='city',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='cep',
            field=models.IntegerField(default=37540000),
        ),
    ]
