# Generated by Django 4.2.2 on 2023-07-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_citizen_cep_alter_city_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='cep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='cep',
            field=models.IntegerField(null=True),
        ),
    ]
