# Generated by Django 4.2.3 on 2023-07-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_occurrence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
