# Generated by Django 4.2.3 on 2023-07-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_occurrence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='city_comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='concluded',
            field=models.CharField(default='Em aberto', max_length=10),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='image',
            field=models.ImageField(default='occurrences/occurrenceVoid.png', null=True, upload_to='occurrences/'),
        ),
    ]
