# Generated by Django 4.2.3 on 2023-07-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_occurrence_city_comment_occurrence_concluded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='priority',
        ),
    ]
