# Generated by Django 4.2.3 on 2023-07-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_occurrence_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='city_comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='user_comment',
            field=models.TextField(max_length=1000),
        ),
    ]
